- name: App Setup
  ansible.builtin.import:
    name: common
    tasks_from: app-setup

- name: Configuring App Service
  ansible.builtin.import:
    name: common
    tasks_from: systemd-config

- name: Installing Maven
  ansible.builtin.import:
    name: common
    tasks_from: java

- name: Configuring Schema
  ansible.builtin.import:
    name: common
    tasks_from: mysql_schema

- name: Enabling and Restarting App
  ansible.builtin.import:
    name: common
    tasks_from: start.yaml