- name: Hello World
  hosts: localhost
  tasks:
  - name: Run Playbook
    ansible.builtin.debug:
      msg: "Hello World"

- name: Earth
  hosts: lo
  tasks:
  - name:Run Playbook
    ansible.builtin.debug:
      msg:  "Earth"