- name: Configuring YUM Erlang Repo
  ansible.builtin.shell:   curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configuring YUM Rabbitmq Repo
  ansible.builtin.shell:  curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installing RabbitMq
  ansible.builtin.package:
    name: rabbitmq-server
    state:  present

- name: Starting Service
  ansible.builtin.import:
    name: common
    tasks_from: start

- name: Creating User and Setting Permissions for RabbitMQ
  ansible.builtin.shell:  rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"