- name: Configuring YUM Erlang Repo
  ansible.builtin.shell:   curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configuring YUM Rabbitmq Repo
  ansible.builtin.shell:  curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installing RabbitMq
  ansible.builtin.package:
    name: rabbitmq-server
    state:  present

- name: Reloading Daemon
  ansible.builtin.systemd_service:
    daemon_reload:  true

- name: "Enabling and Starting {{component}} Service"
  ansible.builtin.service:
    name: rabbitmq-server
    state:  restarted
    enabled:  yes

- name: Creating User and Setting Permissions for RabbitMQ
  ansible.builtin.shell:  rabbitmqctl add_user {{rq_user}} {{rq_password}} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"