- name: Disabling Old Nodejs and Enabling New Nodejs Version
  ansible.builtin.shell:  dnf module disable nodejs -y; dnf module enable nodejs:18 -y;

- name: Installing Nodejs
  ansible.builtin.package:
    name: nodejs
    state:  present

- name: Installing Dependencies
  ansible.builtin.shell:  npm install ;
  args:
    chdir:  /app