- name: Reloading Daemon
  ansible.builtin.systemd_service:
    daemon_reload:  true

- name: Enabling and Starting Service
  ansible.builtin.service:
    name: {{component}}
    state:  restarted
    enabled:  yes