- name: MYSQL
  hosts:  mysql
  become: yes
  tasks:
  - name: Disabling Old Mysql Version
    ansible.builtin.shell:  dnf module disable mysql -y;
  
  - name: Creating Mysql Repo
    ansible.builtin.copy:
      src:  mysql.repo
      dest: /etc/yum.repos.d/

  - name: Installing Mysql 
    ansible.builtin.package:
      name: mysql-community-server
      state:  present
  
  - name: Enabling and Starting Mysql
    ansible.builtin.service:
      name: mysqld
      state:  started
      enabled:  yes

  - name: Setting Root Password For Mysql
    ansible.builtin.shell:  mysql_secure_installation --set-root-pass RoboShop@1
